//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1.ChatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.ChatServiceSoap")]
    public interface ChatServiceSoap {
        
        // CODEGEN: Generating message contract since element name ShowTheTextResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowTheText", ReplyAction="*")]
        App1.ChatServiceReference.ShowTheTextResponse ShowTheText(App1.ChatServiceReference.ShowTheTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowTheText", ReplyAction="*")]
        System.Threading.Tasks.Task<App1.ChatServiceReference.ShowTheTextResponse> ShowTheTextAsync(App1.ChatServiceReference.ShowTheTextRequest request);
        
        // CODEGEN: Generating message contract since element name SimpleFunctionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimpleFunction", ReplyAction="*")]
        App1.ChatServiceReference.SimpleFunctionResponse SimpleFunction(App1.ChatServiceReference.SimpleFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimpleFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<App1.ChatServiceReference.SimpleFunctionResponse> SimpleFunctionAsync(App1.ChatServiceReference.SimpleFunctionRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectUser", ReplyAction="*")]
        App1.ChatServiceReference.ConnectUserResponse ConnectUser(App1.ChatServiceReference.ConnectUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectUser", ReplyAction="*")]
        System.Threading.Tasks.Task<App1.ChatServiceReference.ConnectUserResponse> ConnectUserAsync(App1.ChatServiceReference.ConnectUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Connect", ReplyAction="*")]
        void Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Connect", ReplyAction="*")]
        System.Threading.Tasks.Task ConnectAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowTheTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowTheText", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.ShowTheTextRequestBody Body;
        
        public ShowTheTextRequest() {
        }
        
        public ShowTheTextRequest(App1.ChatServiceReference.ShowTheTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowTheTextRequestBody {
        
        public ShowTheTextRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowTheTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowTheTextResponse", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.ShowTheTextResponseBody Body;
        
        public ShowTheTextResponse() {
        }
        
        public ShowTheTextResponse(App1.ChatServiceReference.ShowTheTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowTheTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowTheTextResult;
        
        public ShowTheTextResponseBody() {
        }
        
        public ShowTheTextResponseBody(string ShowTheTextResult) {
            this.ShowTheTextResult = ShowTheTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimpleFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimpleFunction", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.SimpleFunctionRequestBody Body;
        
        public SimpleFunctionRequest() {
        }
        
        public SimpleFunctionRequest(App1.ChatServiceReference.SimpleFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimpleFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public SimpleFunctionRequestBody() {
        }
        
        public SimpleFunctionRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimpleFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimpleFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.SimpleFunctionResponseBody Body;
        
        public SimpleFunctionResponse() {
        }
        
        public SimpleFunctionResponse(App1.ChatServiceReference.SimpleFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimpleFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SimpleFunctionResult;
        
        public SimpleFunctionResponseBody() {
        }
        
        public SimpleFunctionResponseBody(string SimpleFunctionResult) {
            this.SimpleFunctionResult = SimpleFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectUser", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.ConnectUserRequestBody Body;
        
        public ConnectUserRequest() {
        }
        
        public ConnectUserRequest(App1.ChatServiceReference.ConnectUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConnectUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userId;
        
        public ConnectUserRequestBody() {
        }
        
        public ConnectUserRequestBody(string userName, int userId) {
            this.userName = userName;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public App1.ChatServiceReference.ConnectUserResponseBody Body;
        
        public ConnectUserResponse() {
        }
        
        public ConnectUserResponse(App1.ChatServiceReference.ConnectUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConnectUserResponseBody {
        
        public ConnectUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChatServiceSoapChannel : App1.ChatServiceReference.ChatServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceSoapClient : System.ServiceModel.ClientBase<App1.ChatServiceReference.ChatServiceSoap>, App1.ChatServiceReference.ChatServiceSoap {
        
        public ChatServiceSoapClient() {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App1.ChatServiceReference.ShowTheTextResponse App1.ChatServiceReference.ChatServiceSoap.ShowTheText(App1.ChatServiceReference.ShowTheTextRequest request) {
            return base.Channel.ShowTheText(request);
        }
        
        public string ShowTheText() {
            App1.ChatServiceReference.ShowTheTextRequest inValue = new App1.ChatServiceReference.ShowTheTextRequest();
            inValue.Body = new App1.ChatServiceReference.ShowTheTextRequestBody();
            App1.ChatServiceReference.ShowTheTextResponse retVal = ((App1.ChatServiceReference.ChatServiceSoap)(this)).ShowTheText(inValue);
            return retVal.Body.ShowTheTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App1.ChatServiceReference.ShowTheTextResponse> App1.ChatServiceReference.ChatServiceSoap.ShowTheTextAsync(App1.ChatServiceReference.ShowTheTextRequest request) {
            return base.Channel.ShowTheTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<App1.ChatServiceReference.ShowTheTextResponse> ShowTheTextAsync() {
            App1.ChatServiceReference.ShowTheTextRequest inValue = new App1.ChatServiceReference.ShowTheTextRequest();
            inValue.Body = new App1.ChatServiceReference.ShowTheTextRequestBody();
            return ((App1.ChatServiceReference.ChatServiceSoap)(this)).ShowTheTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App1.ChatServiceReference.SimpleFunctionResponse App1.ChatServiceReference.ChatServiceSoap.SimpleFunction(App1.ChatServiceReference.SimpleFunctionRequest request) {
            return base.Channel.SimpleFunction(request);
        }
        
        public string SimpleFunction(int a, int b) {
            App1.ChatServiceReference.SimpleFunctionRequest inValue = new App1.ChatServiceReference.SimpleFunctionRequest();
            inValue.Body = new App1.ChatServiceReference.SimpleFunctionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            App1.ChatServiceReference.SimpleFunctionResponse retVal = ((App1.ChatServiceReference.ChatServiceSoap)(this)).SimpleFunction(inValue);
            return retVal.Body.SimpleFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App1.ChatServiceReference.SimpleFunctionResponse> App1.ChatServiceReference.ChatServiceSoap.SimpleFunctionAsync(App1.ChatServiceReference.SimpleFunctionRequest request) {
            return base.Channel.SimpleFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<App1.ChatServiceReference.SimpleFunctionResponse> SimpleFunctionAsync(int a, int b) {
            App1.ChatServiceReference.SimpleFunctionRequest inValue = new App1.ChatServiceReference.SimpleFunctionRequest();
            inValue.Body = new App1.ChatServiceReference.SimpleFunctionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((App1.ChatServiceReference.ChatServiceSoap)(this)).SimpleFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App1.ChatServiceReference.ConnectUserResponse App1.ChatServiceReference.ChatServiceSoap.ConnectUser(App1.ChatServiceReference.ConnectUserRequest request) {
            return base.Channel.ConnectUser(request);
        }
        
        public void ConnectUser(string userName, int userId) {
            App1.ChatServiceReference.ConnectUserRequest inValue = new App1.ChatServiceReference.ConnectUserRequest();
            inValue.Body = new App1.ChatServiceReference.ConnectUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userId = userId;
            App1.ChatServiceReference.ConnectUserResponse retVal = ((App1.ChatServiceReference.ChatServiceSoap)(this)).ConnectUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App1.ChatServiceReference.ConnectUserResponse> App1.ChatServiceReference.ChatServiceSoap.ConnectUserAsync(App1.ChatServiceReference.ConnectUserRequest request) {
            return base.Channel.ConnectUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<App1.ChatServiceReference.ConnectUserResponse> ConnectUserAsync(string userName, int userId) {
            App1.ChatServiceReference.ConnectUserRequest inValue = new App1.ChatServiceReference.ConnectUserRequest();
            inValue.Body = new App1.ChatServiceReference.ConnectUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userId = userId;
            return ((App1.ChatServiceReference.ChatServiceSoap)(this)).ConnectUserAsync(inValue);
        }
        
        public void Connect() {
            base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
    }
}
